language: ruby
cache:
- bundler
install:
- bundle install
rvm:
- 2.0
- 2.1
- 2.2
- 2.3.0
notifications:
  email:
    recipients:
    - sensu-plugin@sensu-plugins.io
    on_success: change
    on_failure: always
script:
- bundle exec rake default
- gem build sensu-plugins-github.gemspec
- gem install sensu-plugins-github-*.gem
deploy:
  provider: rubygems
  api_key:
    secure: N2uIPHI4FLC7gVXnODfFuWbTlWazGr6EA7ZvBuRTUUKxohV9V72IJzyd9KUBx+1EmDCBanmdolZQzQPaTWJ0inahjgSUSWp3jR8buCxzQJLUaXp20hbWj2oCypwiLoNXsZiclI+VSh9mGqADx9FijtKv2v8xkEeepJ9Xve4SUo8=
  gem: sensu-plugins-github
  on:
    tags: true
    all_branches: true
    rvm: 2.1
    rvm: 2.2
    rvm: 2.3.0
    repo: sensu-plugins/sensu-plugins-github
